export const CATEGORIES = [
  { id: 'animals', label: 'Animals', icon: 'PawPrint' },
  { id: 'aerospace', label: 'Aerospace', icon: 'Globe' },
  { id: 'robotics', label: 'Robotics', icon: 'Bot' },
  { id: 'architecture', label: 'Architecture', icon: 'Shield' },
];

export const OBJECT_LIBRARY = [
  // --- ANIMALS ---
  {
    id: 'lion',
    name: 'Majestic African Lion',
    category: 'animals',
    description: 'Sculpted athletic quadruped lion with golden amber mane and tail',
    icon: 'Flame',
    defaultScale: 0.85,
    color: '#FFB800',
  },
  {
    id: 'wolf',
    name: 'Alpha Timber Wolf',
    category: 'animals',
    description: 'Sleek hunting posture wolf with pointed ears and bushy tail',
    icon: 'Zap',
    defaultScale: 0.85,
    color: '#00F0FF',
  },
  {
    id: 'horse',
    name: 'Stallion Horse',
    category: 'animals',
    description: 'Powerful equestrian stallion with arched neck and flowing mane',
    icon: 'Heart',
    defaultScale: 0.85,
    color: '#FF5B35',
  },
  {
    id: 'eagle',
    name: 'Soaring Golden Eagle',
    category: 'animals',
    description: 'Raptorial soaring eagle with broad wingspan on rock pedestal',
    icon: 'Feather',
    defaultScale: 0.85,
    color: '#FFB800',
  },

  // --- AEROSPACE ---
  {
    id: 'satellite',
    name: 'Orbital Satellite',
    category: 'aerospace',
    description: 'High-gain telecom satellite with dual solar arrays and sensor dish',
    icon: 'Globe',
    defaultScale: 0.85,
    color: '#00F0FF',
  },
  {
    id: 'drone',
    name: 'Recon Quadcopter',
    category: 'aerospace',
    description: 'Tactical UAV with 4 rotor rings and gimbal-mounted optical camera',
    icon: 'Zap',
    defaultScale: 0.9,
    color: '#00FF66',
  },
  {
    id: 'rocket',
    name: 'Interstellar Cruiser',
    category: 'aerospace',
    description: 'Deep-space command vessel with swept delta wings and thruster rings',
    icon: 'Flame',
    defaultScale: 0.8,
    color: '#FFB800',
  },
  {
    id: 'station',
    name: 'Space Habitat',
    category: 'aerospace',
    description: 'Toroidal O-ring space station with docking hub and solar masts',
    icon: 'Circle',
    defaultScale: 0.8,
    color: '#A855F7',
  },

  // --- ROBOTICS ---
  {
    id: 'rover',
    name: 'Cyber Rover',
    category: 'robotics',
    description: '6-wheeled planetary exploration rover with mast camera turret',
    icon: 'Cpu',
    defaultScale: 0.85,
    color: '#FF5B35',
  },
  {
    id: 'mech',
    name: 'Sentinel Mech',
    category: 'robotics',
    description: 'Heavy bipedal defense mech with shoulder sensor pods and glowing visor',
    icon: 'Shield',
    defaultScale: 0.85,
    color: '#00F0FF',
  },
  {
    id: 'arm',
    name: 'Industrial Robot Arm',
    category: 'robotics',
    description: '6-axis precision robotic arm with articulated elbow and gripper claws',
    icon: 'Bot',
    defaultScale: 0.85,
    color: '#FFB800',
  },
  {
    id: 'cyborg',
    name: 'AI Security Pod',
    category: 'robotics',
    description: 'Autonomous spherical recon drone with rotating scanner rings',
    icon: 'Hexagon',
    defaultScale: 0.85,
    color: '#00FF66',
  },

  // --- ARCHITECTURE ---
  {
    id: 'pavilion',
    name: 'Modern Pavilion',
    category: 'architecture',
    description: 'Futuristic architectural pavilion with curved canopy and glass walls',
    icon: 'Box',
    defaultScale: 0.85,
    color: '#A855F7',
  },
  {
    id: 'tower',
    name: 'Helix Skyscraper',
    category: 'architecture',
    description: 'Parametric skyscraper with helical floor plates and structural spire',
    icon: 'Triangle',
    defaultScale: 0.8,
    color: '#00F0FF',
  },
  {
    id: 'bridge',
    name: 'Suspension Bridge',
    category: 'architecture',
    description: 'Cable-stayed bridge engineering model with twin pylons and deck',
    icon: 'Feather',
    defaultScale: 0.85,
    color: '#FF5B35',
  },
  {
    id: 'chair',
    name: 'Ethereal Chair',
    category: 'architecture',
    description: 'Holographic designer chair with curved backrest and chrome legs',
    icon: 'Armchair',
    defaultScale: 0.85,
    color: '#FF0055',
  },
];
